[build]
  command = 'npm run ci:build'
  publish = 'out'

[template]
  incoming-hooks = ["Uniform"]

[template.environment]
  CONTENTFUL_SPACE_ID = 'Contentful Space ID'
  CONTENTFUL_ENVIRONMENT = 'Contentful Environment'
  CONTENTFUL_CDA_ACCESS_TOKEN = 'Contentful Delivery API Key'
  CONTENTFUL_CPA_ACCESS_TOKEN = 'Contentful Preview API Key'
  UNIFORM_API_KEY='Uniform Optimize API Key'
  GA_UA_ID='Google Analytics ID (optional)'
  BIGCOMMERCE_STORE_HASH='Store hash from BigCommerce'
  BIGCOMMERCE_TOKEN='API token from BigCommerce'
  UNIFORM_PRESENTATION_API_HOST = 'Uniform API host'
  UNIFORM_PRESENTATION_API_TOKEN='Your UPM API Key'
  UNIFORM_CLI_BASE_URL='The Uniform Optimize API host for manifests'
  NPM_TOKEN='The NPM token you got from us'

# Stores the next cache between builds for faster build time
[[plugins]]
  package = "netlify-plugin-cache-nextjs"
